name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: base metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.base.svg
          token: ${{ secrets.TOKEN }}
          base: header
          config_order: base.header
      - name: apple music
        uses: lowlighter/metrics@latest
        with:
          filename: apple.music.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          plugin_music: yes
          plugin_music_provider: apple
          plugin_music_playlist: https://embed.music.apple.com/cn/playlist/github-suggest/pl.u-Ymb0962fP0baNAN
      - name: last_fm
        uses: lowlighter/metrics@latest
        with:
          filename: last.fm.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          plugin_music_token: ${{ secrets.LASTFM }}
          plugin_music: yes
          plugin_music_provider: lastfm
          
